// <auto-generated />
using System;
using Importer.WApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Importer.WApp.Migrations.PokemonDb
{
    [DbContext(typeof(PokemonDbContext))]
    partial class PokemonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("Importer.Domain.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesWatched")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("Importer.Domain.Entities.Import", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("Importer.Domain.Entities.MatchPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MatchPokemon");
                });

            modelBuilder.Entity("Importer.Domain.Entities.MyPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedIn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PokemonId1")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("PokemonId1");

                    b.ToTable("MyPokemons");
                });

            modelBuilder.Entity("Importer.Domain.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 49,
                            Defense = 49,
                            HP = 45,
                            Name = "Bulbasaur",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 318,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Attack = 49,
                            Defense = 49,
                            HP = 47,
                            Name = "Ivysaur",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 405,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Attack = 49,
                            Defense = 49,
                            HP = 58,
                            Name = "Venusaur",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 525,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Attack = 49,
                            Defense = 49,
                            HP = 33,
                            Name = "Charmander",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 625,
                            Type = 6
                        },
                        new
                        {
                            Id = 5,
                            Attack = 49,
                            Defense = 49,
                            HP = 87,
                            Name = "Charmeleon",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 309,
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Attack = 49,
                            Defense = 49,
                            HP = 26,
                            Name = "Charizard",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 578,
                            Type = 10
                        },
                        new
                        {
                            Id = 7,
                            Attack = 49,
                            Defense = 49,
                            HP = 45,
                            Name = "Squirtle",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 523,
                            Type = 7
                        },
                        new
                        {
                            Id = 8,
                            Attack = 95,
                            Defense = 49,
                            HP = 45,
                            Name = "Wartortle",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 643,
                            Type = 5
                        },
                        new
                        {
                            Id = 9,
                            Attack = 49,
                            Defense = 49,
                            HP = 15,
                            Name = "Blastoise",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 641,
                            Type = 8
                        },
                        new
                        {
                            Id = 10,
                            Attack = 49,
                            Defense = 49,
                            HP = 45,
                            Name = "Caterpie",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 312,
                            Type = 13
                        },
                        new
                        {
                            Id = 11,
                            Attack = 96,
                            Defense = 49,
                            HP = 45,
                            Name = "Metapod",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 541,
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            Attack = 49,
                            Defense = 49,
                            HP = 45,
                            Name = "Butterfree",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 453,
                            Type = 11
                        },
                        new
                        {
                            Id = 13,
                            Attack = 48,
                            Defense = 49,
                            HP = 45,
                            Name = "Weedle",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 245,
                            Type = 9
                        },
                        new
                        {
                            Id = 14,
                            Attack = 49,
                            Defense = 49,
                            HP = 45,
                            Name = "Kakuna",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 513,
                            Type = 12
                        },
                        new
                        {
                            Id = 15,
                            Attack = 49,
                            Defense = 49,
                            HP = 45,
                            Name = "Beedrill",
                            Speed = 45,
                            SpeedAttack = 65,
                            SpeedDefense = 65,
                            Total = 316,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Importer.Domain.Entities.MyPokemon", b =>
                {
                    b.HasOne("Importer.Domain.Entities.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Importer.Domain.Entities.Pokemon", null)
                        .WithMany("MyPokemons")
                        .HasForeignKey("PokemonId1");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Importer.Domain.Entities.Pokemon", b =>
                {
                    b.Navigation("MyPokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
